// Generated by gencpp from file mario_kart/itemRequest.msg
// DO NOT EDIT!


#ifndef MARIO_KART_MESSAGE_ITEMREQUEST_H
#define MARIO_KART_MESSAGE_ITEMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mario_kart
{
template <class ContainerAllocator>
struct itemRequest_
{
  typedef itemRequest_<ContainerAllocator> Type;

  itemRequest_()
    : vel(0.0)
    , omega(0.0)  {
    }
  itemRequest_(const ContainerAllocator& _alloc)
    : vel(0.0)
    , omega(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_type;
  _vel_type vel;

   typedef float _omega_type;
  _omega_type omega;





  typedef boost::shared_ptr< ::mario_kart::itemRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mario_kart::itemRequest_<ContainerAllocator> const> ConstPtr;

}; // struct itemRequest_

typedef ::mario_kart::itemRequest_<std::allocator<void> > itemRequest;

typedef boost::shared_ptr< ::mario_kart::itemRequest > itemRequestPtr;
typedef boost::shared_ptr< ::mario_kart::itemRequest const> itemRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mario_kart::itemRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mario_kart::itemRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mario_kart::itemRequest_<ContainerAllocator1> & lhs, const ::mario_kart::itemRequest_<ContainerAllocator2> & rhs)
{
  return lhs.vel == rhs.vel &&
    lhs.omega == rhs.omega;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mario_kart::itemRequest_<ContainerAllocator1> & lhs, const ::mario_kart::itemRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mario_kart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mario_kart::itemRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mario_kart::itemRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mario_kart::itemRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mario_kart::itemRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mario_kart::itemRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mario_kart::itemRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mario_kart::itemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eabcf020b6514d3ff27102ac1d24cb0e";
  }

  static const char* value(const ::mario_kart::itemRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeabcf020b6514d3fULL;
  static const uint64_t static_value2 = 0xf27102ac1d24cb0eULL;
};

template<class ContainerAllocator>
struct DataType< ::mario_kart::itemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mario_kart/itemRequest";
  }

  static const char* value(const ::mario_kart::itemRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mario_kart::itemRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request message types\n"
"float32 vel\n"
"float32 omega\n"
"\n"
;
  }

  static const char* value(const ::mario_kart::itemRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mario_kart::itemRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel);
      stream.next(m.omega);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct itemRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mario_kart::itemRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mario_kart::itemRequest_<ContainerAllocator>& v)
  {
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
    s << indent << "omega: ";
    Printer<float>::stream(s, indent + "  ", v.omega);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARIO_KART_MESSAGE_ITEMREQUEST_H
