// Generated by gencpp from file mario_kart/itemResponse.msg
// DO NOT EDIT!


#ifndef MARIO_KART_MESSAGE_ITEMRESPONSE_H
#define MARIO_KART_MESSAGE_ITEMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace mario_kart
{
template <class ContainerAllocator>
struct itemResponse_
{
  typedef itemResponse_<ContainerAllocator> Type;

  itemResponse_()
    : cmd()  {
    }
  itemResponse_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::mario_kart::itemResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mario_kart::itemResponse_<ContainerAllocator> const> ConstPtr;

}; // struct itemResponse_

typedef ::mario_kart::itemResponse_<std::allocator<void> > itemResponse;

typedef boost::shared_ptr< ::mario_kart::itemResponse > itemResponsePtr;
typedef boost::shared_ptr< ::mario_kart::itemResponse const> itemResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mario_kart::itemResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mario_kart::itemResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mario_kart::itemResponse_<ContainerAllocator1> & lhs, const ::mario_kart::itemResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mario_kart::itemResponse_<ContainerAllocator1> & lhs, const ::mario_kart::itemResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mario_kart

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mario_kart::itemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mario_kart::itemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mario_kart::itemResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mario_kart::itemResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mario_kart::itemResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mario_kart::itemResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mario_kart::itemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0c47a2b42626c8e0bd2a277053c6c62";
  }

  static const char* value(const ::mario_kart::itemResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0c47a2b42626c8eULL;
  static const uint64_t static_value2 = 0x0bd2a277053c6c62ULL;
};

template<class ContainerAllocator>
struct DataType< ::mario_kart::itemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mario_kart/itemResponse";
  }

  static const char* value(const ::mario_kart::itemResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mario_kart::itemResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response message types\n"
"geometry_msgs/Twist cmd\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mario_kart::itemResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mario_kart::itemResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct itemResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mario_kart::itemResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mario_kart::itemResponse_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARIO_KART_MESSAGE_ITEMRESPONSE_H
